services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    user: 1000:1000
    hostname: sartre
    command: serve
    volumes:
      - ${DOCKER_ROOT:-.}/diun/data/db:/data
      - ${DOCKER_ROOT:-.}/diun/data/config.yml:/diun.yml:ro
    environment:
      - TZ=Europe/Madrid
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: unless-stopped
